# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhltvmsvc
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  redis:
    extends:
      file: ./redis.yml
      service: redis
  jhipster-registry:
    extends:
      file: ./jhipster-registry.yml
      service: jhipster-registry
