package id.co.kusumakazu.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AiSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiSessionAllPropertiesEquals(AiSession expected, AiSession actual) {
        assertAiSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertAiSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiSessionAllUpdatablePropertiesEquals(AiSession expected, AiSession actual) {
        assertAiSessionUpdatableFieldsEquals(expected, actual);
        assertAiSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiSessionAutoGeneratedPropertiesEquals(AiSession expected, AiSession actual) {
        assertThat(expected)
            .as("Verify AiSession auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiSessionUpdatableFieldsEquals(AiSession expected, AiSession actual) {
        assertThat(expected)
            .as("Verify AiSession relevant properties")
            .satisfies(e -> assertThat(e.getSessionName()).as("check sessionName").isEqualTo(actual.getSessionName()))
            .satisfies(e -> assertThat(e.getSessionCreatedTime()).as("check sessionCreatedTime").isEqualTo(actual.getSessionCreatedTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiSessionUpdatableRelationshipsEquals(AiSession expected, AiSession actual) {}
}
