package id.co.kusumakazu.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SessionMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionMessageAllPropertiesEquals(SessionMessage expected, SessionMessage actual) {
        assertSessionMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertSessionMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionMessageAllUpdatablePropertiesEquals(SessionMessage expected, SessionMessage actual) {
        assertSessionMessageUpdatableFieldsEquals(expected, actual);
        assertSessionMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionMessageAutoGeneratedPropertiesEquals(SessionMessage expected, SessionMessage actual) {
        assertThat(expected)
            .as("Verify SessionMessage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionMessageUpdatableFieldsEquals(SessionMessage expected, SessionMessage actual) {
        assertThat(expected)
            .as("Verify SessionMessage relevant properties")
            .satisfies(e -> assertThat(e.getRole()).as("check role").isEqualTo(actual.getRole()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()))
            .satisfies(e -> assertThat(e.getAiSessionId()).as("check aiSessionId").isEqualTo(actual.getAiSessionId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionMessageUpdatableRelationshipsEquals(SessionMessage expected, SessionMessage actual) {}
}
